import "./globals.css";

import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Use client-side navigation to check pathname
  // Exclude homepage and other paths from showing Footer
  // This requires 'use client' and usePathname from 'next/navigation'
  // You can add more excluded paths to the array below
  const excludedPaths = ["/"];
  let pathname;
  if (typeof window !== "undefined") {
    // fallback for SSR
    pathname = window.location.pathname;
  }
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/zyk8izc.css"></link>
      </head>
      <body>
        <Header />
        {children}
        {/* Only show Footer if not on excluded paths */}
        {(!excludedPaths.includes(pathname)) && <Footer />}
      </body>
    </html>
  );
}


