import "./globals.css";

import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/zyk8izc.css"></link>
      </head>
      <body className="flex flex-col min-h-screen m-0">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}


